---
apiVersion: v1
offerings:
  - name: deploy-arch-ibm-ocp-virtualization
    kind: solution
    catalog_id: 7df1e4ca-d54c-4fd0-82ce-3d13247308cd
    offering_id: e4e5b526-5a08-4d63-bea6-04417c30583e
    variations:
      - name: quickstart
        mark_ready: true
        install_type: fullstack
