---
apiVersion: v1
offerings:
  - name: deploy-arch-ibm-ocp-vpc
    kind: solution
    catalog_id:
    offering_id:
    variations:
      - name: fully-configurable
        mark_ready: true
        install_type: fullstack
        pre_validation: "tests/scripts/pre-validation-deploy-ocp.sh"
        post_validation: "tests/scripts/post-validation-destroy-ocp.sh"
