---
apiVersion: v1
offerings:
  - name: deploy-arch-ibm-ocp-virtualization
    kind: solution
    catalog_id:
    offering_id:
    variations:
      - name: quickstart
        mark_ready: true
        install_type: fullstack
