apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: {{ .Values.vm.name }}-rootdisk
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.vm.name }}
    kubevirt.io/vm: {{ .Values.vm.name }}
spec:
  source:
    registry:
      url: "docker://{{ .Values.vm.image }}"
  storage:
    storageClassName: {{ .Values.vm.storageClass }}
    accessModes:
      - ReadWriteMany
    volumeMode: Filesystem
    resources:
      requests:
        storage: {{ .Values.vm.diskSize }}
